### ISSUE TITLE
☂️ Make oidc-apps-controller production ready

### ISSUE THREAD

**Issue by nickytd** [gardener/oidc-apps-controller#2]
### Functional completness
- [x] Leverage the `obervability.gardener.cloud/app` common label in g/g https://github.com/gardener/gardener/pull/9385
- [x] Clean TODOs in the code
- [x] Complete e2e tests for all reconcilers #23 

### Configurations
- [x] Add vpaSelector for targets

### Logging
- [x] Review  all log messages

### Monitoring
- [x] Expose controller-runtime metrics
- [ ] Add controller specifics metrics for major runnable actions
  - [ ] certificate rotations
  - [x] token-notifiers
  - [x] target updates
  - [x] webhook mutations 

### Documentation
- [x] Add targets configuration description
